DOMAIN = "synapse"
EVENT_NAMESPACE = "digital_alchemy"
PLATFORMS: list[str] = [
    # "alarm_control_panel",
    "binary_sensor",
    "button",
    "climate",
    "cover",
    "date",
    "datetime",
    "fan",
    "humidifier",
    "image",
    "light",
    "lock",
    "number",
    "remote",
    "scene",
    "select",
    "sensor",
    "siren",
    "switch",
    "text",
    "time",
    "update",
    "valve",
    # "camera",
    # "lawn_mower",
    # "media_player",
    # "notify",
    # "todo_list",
    # "vacuum",
    # "water_heater",
]
