DOMAIN = "synapse"

PLATFORMS: list[str] = [
    "binary_sensor",
    "button",
    "number",
    "scene",
    "sensor",
    "switch",
]


# PLATFORMS: list[str] = [
#     "alarm_control_panel",
#     "binary_sensor",
#     "button",
#     "camera",
#     "climate",
#     "cover",
#     "date",
#     "datetime",
#     "fan",
#     "humidifier",
#     "image",
#     "lawn_mower",
#     "light",
#     "lock",
#     "media_player",
#     "notify",
#     "number",
#     "number",
#     "remote",
#     "scene",
#     "select",
#     "sensor",
#     "siren",
#     "switch",
#     "text",
#     "time",
#     "todo_list",
#     "update",
#     "vacuum",
#     "valve",
#     "water_heater",
# ]
